apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeName: ebs-pv
  volumeMode: Block
  resources:
    requests:
      storage: 4Gi